// Copyright (c) 2014 Dataence, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is automatically generated by genfsm.go. Please DO NOT modify.
// This file was generated at 2018-07-31 21:30:10.828515386 +0200 CEST m=+0.001385074.

package sequence

func matchRequestMethods(ss string) int {
	var (
		m int			// match length
		s int			// state
	)

loop:
	for _, b := range ss {
		switch s {
		case 0:
			switch b {
			case 'H', 'h':
				s = 1
			case 'G', 'g':
				s = 6
			case 'P', 'p':
				s = 10
			case 'D', 'd':
				s = 18
			case 'C', 'c':
				s = 25
			case 'O', 'o':
				s = 33
			case 'T', 't':
				s = 41
			case 'M', 'm':
				s = 66
			case 'L', 'l':
				s = 79
			case 'U', 'u':
				s = 84
			case 'V', 'v':
				s = 91
			case 'R', 'r':
				s = 138
			case 'B', 'b':
				s = 164
			case 'I', 'i':
				s = 186
			default:
				break loop
			}
		case 1:
			switch b {
			case 'E', 'e':
				s = 2
			default:
				break loop
			}
		case 2:
			switch b {
			case 'A', 'a':
				s = 3
			default:
				break loop
			}
		case 3:
			switch b {
			case 'D', 'd':
				s = 4
			default:
				break loop
			}
		case 4:
			switch b {
			case ' ':
				s = 5
				m = 4
				// HEAD  - final
			default:
				break loop
			}
		case 6:
			switch b {
			case 'E', 'e':
				s = 7
			default:
				break loop
			}
		case 7:
			switch b {
			case 'T', 't':
				s = 8
			default:
				break loop
			}
		case 8:
			switch b {
			case ' ':
				s = 9
				m = 3
				// GET  - final
			default:
				break loop
			}
		case 10:
			switch b {
			case 'U', 'u':
				s = 11
			case 'O', 'o':
				s = 14
			case 'A', 'a':
				s = 47
			case 'R', 'r':
				s = 52
			default:
				break loop
			}
		case 11:
			switch b {
			case 'T', 't':
				s = 12
			default:
				break loop
			}
		case 12:
			switch b {
			case ' ':
				s = 13
				m = 3
				// PUT  - final
			default:
				break loop
			}
		case 14:
			switch b {
			case 'S', 's':
				s = 15
			default:
				break loop
			}
		case 15:
			switch b {
			case 'T', 't':
				s = 16
			default:
				break loop
			}
		case 16:
			switch b {
			case ' ':
				s = 17
				m = 4
				// POST  - final
			default:
				break loop
			}
		case 18:
			switch b {
			case 'E', 'e':
				s = 19
			default:
				break loop
			}
		case 19:
			switch b {
			case 'L', 'l':
				s = 20
			default:
				break loop
			}
		case 20:
			switch b {
			case 'E', 'e':
				s = 21
			default:
				break loop
			}
		case 21:
			switch b {
			case 'T', 't':
				s = 22
			default:
				break loop
			}
		case 22:
			switch b {
			case 'E', 'e':
				s = 23
			default:
				break loop
			}
		case 23:
			switch b {
			case ' ':
				s = 24
				m = 6
				// DELETE  - final
			default:
				break loop
			}
		case 25:
			switch b {
			case 'O', 'o':
				s = 26
			case 'H', 'h':
				s = 107
			default:
				break loop
			}
		case 26:
			switch b {
			case 'N', 'n':
				s = 27
			case 'P', 'p':
				s = 72
			default:
				break loop
			}
		case 27:
			switch b {
			case 'N', 'n':
				s = 28
			default:
				break loop
			}
		case 28:
			switch b {
			case 'E', 'e':
				s = 29
			default:
				break loop
			}
		case 29:
			switch b {
			case 'C', 'c':
				s = 30
			default:
				break loop
			}
		case 30:
			switch b {
			case 'T', 't':
				s = 31
			default:
				break loop
			}
		case 31:
			switch b {
			case ' ':
				s = 32
				m = 7
				// CONNECT  - final
			default:
				break loop
			}
		case 33:
			switch b {
			case 'P', 'p':
				s = 34
			default:
				break loop
			}
		case 34:
			switch b {
			case 'T', 't':
				s = 35
			default:
				break loop
			}
		case 35:
			switch b {
			case 'I', 'i':
				s = 36
			default:
				break loop
			}
		case 36:
			switch b {
			case 'O', 'o':
				s = 37
			default:
				break loop
			}
		case 37:
			switch b {
			case 'N', 'n':
				s = 38
			default:
				break loop
			}
		case 38:
			switch b {
			case 'S', 's':
				s = 39
			default:
				break loop
			}
		case 39:
			switch b {
			case ' ':
				s = 40
				m = 7
				// OPTIONS  - final
			default:
				break loop
			}
		case 41:
			switch b {
			case 'R', 'r':
				s = 42
			default:
				break loop
			}
		case 42:
			switch b {
			case 'A', 'a':
				s = 43
			default:
				break loop
			}
		case 43:
			switch b {
			case 'C', 'c':
				s = 44
			default:
				break loop
			}
		case 44:
			switch b {
			case 'E', 'e':
				s = 45
			default:
				break loop
			}
		case 45:
			switch b {
			case ' ':
				s = 46
				m = 5
				// TRACE  - final
			default:
				break loop
			}
		case 47:
			switch b {
			case 'T', 't':
				s = 48
			default:
				break loop
			}
		case 48:
			switch b {
			case 'C', 'c':
				s = 49
			default:
				break loop
			}
		case 49:
			switch b {
			case 'H', 'h':
				s = 50
			default:
				break loop
			}
		case 50:
			switch b {
			case ' ':
				s = 51
				m = 5
				// PATCH  - final
			default:
				break loop
			}
		case 52:
			switch b {
			case 'O', 'o':
				s = 53
			default:
				break loop
			}
		case 53:
			switch b {
			case 'P', 'p':
				s = 54
			default:
				break loop
			}
		case 54:
			switch b {
			case 'F', 'f':
				s = 55
			case 'P', 'p':
				s = 60
			default:
				break loop
			}
		case 55:
			switch b {
			case 'I', 'i':
				s = 56
			default:
				break loop
			}
		case 56:
			switch b {
			case 'N', 'n':
				s = 57
			default:
				break loop
			}
		case 57:
			switch b {
			case 'D', 'd':
				s = 58
			default:
				break loop
			}
		case 58:
			switch b {
			case ' ':
				s = 59
				m = 8
				// PROPFIND  - final
			default:
				break loop
			}
		case 60:
			switch b {
			case 'A', 'a':
				s = 61
			default:
				break loop
			}
		case 61:
			switch b {
			case 'T', 't':
				s = 62
			default:
				break loop
			}
		case 62:
			switch b {
			case 'C', 'c':
				s = 63
			default:
				break loop
			}
		case 63:
			switch b {
			case 'H', 'h':
				s = 64
			default:
				break loop
			}
		case 64:
			switch b {
			case ' ':
				s = 65
				m = 9
				// PROPPATCH  - final
			default:
				break loop
			}
		case 66:
			switch b {
			case 'K', 'k':
				s = 67
			case 'O', 'o':
				s = 75
			case 'E', 'e':
				s = 181
			default:
				break loop
			}
		case 67:
			switch b {
			case 'C', 'c':
				s = 68
			case 'W', 'w':
				s = 145
			case 'A', 'a':
				s = 155
			default:
				break loop
			}
		case 68:
			switch b {
			case 'O', 'o':
				s = 69
			default:
				break loop
			}
		case 69:
			switch b {
			case 'L', 'l':
				s = 70
			default:
				break loop
			}
		case 70:
			switch b {
			case ' ':
				s = 71
				m = 5
				// MKCOL  - final
			default:
				break loop
			}
		case 72:
			switch b {
			case 'Y', 'y':
				s = 73
			default:
				break loop
			}
		case 73:
			switch b {
			case ' ':
				s = 74
				m = 4
				// COPY  - final
			default:
				break loop
			}
		case 75:
			switch b {
			case 'V', 'v':
				s = 76
			default:
				break loop
			}
		case 76:
			switch b {
			case 'E', 'e':
				s = 77
			default:
				break loop
			}
		case 77:
			switch b {
			case ' ':
				s = 78
				m = 4
				// MOVE  - final
			default:
				break loop
			}
		case 79:
			switch b {
			case 'O', 'o':
				s = 80
			case 'A', 'a':
				s = 133
			default:
				break loop
			}
		case 80:
			switch b {
			case 'C', 'c':
				s = 81
			default:
				break loop
			}
		case 81:
			switch b {
			case 'K', 'k':
				s = 82
			default:
				break loop
			}
		case 82:
			switch b {
			case ' ':
				s = 83
				m = 4
				// LOCK  - final
			default:
				break loop
			}
		case 84:
			switch b {
			case 'N', 'n':
				s = 85
			case 'P', 'p':
				s = 127
			default:
				break loop
			}
		case 85:
			switch b {
			case 'L', 'l':
				s = 86
			case 'C', 'c':
				s = 115
			default:
				break loop
			}
		case 86:
			switch b {
			case 'O', 'o':
				s = 87
			default:
				break loop
			}
		case 87:
			switch b {
			case 'C', 'c':
				s = 88
			default:
				break loop
			}
		case 88:
			switch b {
			case 'K', 'k':
				s = 89
			default:
				break loop
			}
		case 89:
			switch b {
			case ' ':
				s = 90
				m = 6
				// UNLOCK  - final
			default:
				break loop
			}
		case 91:
			switch b {
			case 'E', 'e':
				s = 92
			default:
				break loop
			}
		case 92:
			switch b {
			case 'R', 'r':
				s = 93
			default:
				break loop
			}
		case 93:
			switch b {
			case 'S', 's':
				s = 94
			default:
				break loop
			}
		case 94:
			switch b {
			case 'I', 'i':
				s = 95
			default:
				break loop
			}
		case 95:
			switch b {
			case 'O', 'o':
				s = 96
			default:
				break loop
			}
		case 96:
			switch b {
			case 'N', 'n':
				s = 97
			default:
				break loop
			}
		case 97:
			switch b {
			case '_', '':
				s = 98
			default:
				break loop
			}
		case 98:
			switch b {
			case 'C', 'c':
				s = 99
			default:
				break loop
			}
		case 99:
			switch b {
			case 'O', 'o':
				s = 100
			default:
				break loop
			}
		case 100:
			switch b {
			case 'N', 'n':
				s = 101
			default:
				break loop
			}
		case 101:
			switch b {
			case 'T', 't':
				s = 102
			default:
				break loop
			}
		case 102:
			switch b {
			case 'R', 'r':
				s = 103
			default:
				break loop
			}
		case 103:
			switch b {
			case 'O', 'o':
				s = 104
			default:
				break loop
			}
		case 104:
			switch b {
			case 'L', 'l':
				s = 105
			default:
				break loop
			}
		case 105:
			switch b {
			case ' ':
				s = 106
				m = 15
				// VERSION_CONTROL  - final
			default:
				break loop
			}
		case 107:
			switch b {
			case 'E', 'e':
				s = 108
			default:
				break loop
			}
		case 108:
			switch b {
			case 'C', 'c':
				s = 109
			default:
				break loop
			}
		case 109:
			switch b {
			case 'K', 'k':
				s = 110
			default:
				break loop
			}
		case 110:
			switch b {
			case 'O', 'o':
				s = 111
			case 'I', 'i':
				s = 124
			default:
				break loop
			}
		case 111:
			switch b {
			case 'U', 'u':
				s = 112
			default:
				break loop
			}
		case 112:
			switch b {
			case 'T', 't':
				s = 113
			default:
				break loop
			}
		case 113:
			switch b {
			case ' ':
				s = 114
				m = 8
				// CHECKOUT  - final
			default:
				break loop
			}
		case 115:
			switch b {
			case 'H', 'h':
				s = 116
			default:
				break loop
			}
		case 116:
			switch b {
			case 'E', 'e':
				s = 117
			default:
				break loop
			}
		case 117:
			switch b {
			case 'C', 'c':
				s = 118
			default:
				break loop
			}
		case 118:
			switch b {
			case 'K', 'k':
				s = 119
			default:
				break loop
			}
		case 119:
			switch b {
			case 'O', 'o':
				s = 120
			default:
				break loop
			}
		case 120:
			switch b {
			case 'U', 'u':
				s = 121
			default:
				break loop
			}
		case 121:
			switch b {
			case 'T', 't':
				s = 122
			default:
				break loop
			}
		case 122:
			switch b {
			case ' ':
				s = 123
				m = 10
				// UNCHECKOUT  - final
			default:
				break loop
			}
		case 124:
			switch b {
			case 'N', 'n':
				s = 125
			default:
				break loop
			}
		case 125:
			switch b {
			case ' ':
				s = 126
				m = 7
				// CHECKIN  - final
			default:
				break loop
			}
		case 127:
			switch b {
			case 'D', 'd':
				s = 128
			default:
				break loop
			}
		case 128:
			switch b {
			case 'A', 'a':
				s = 129
			default:
				break loop
			}
		case 129:
			switch b {
			case 'T', 't':
				s = 130
			default:
				break loop
			}
		case 130:
			switch b {
			case 'E', 'e':
				s = 131
			default:
				break loop
			}
		case 131:
			switch b {
			case ' ':
				s = 132
				m = 6
				// UPDATE  - final
			default:
				break loop
			}
		case 133:
			switch b {
			case 'B', 'b':
				s = 134
			default:
				break loop
			}
		case 134:
			switch b {
			case 'E', 'e':
				s = 135
			default:
				break loop
			}
		case 135:
			switch b {
			case 'L', 'l':
				s = 136
			default:
				break loop
			}
		case 136:
			switch b {
			case ' ':
				s = 137
				m = 5
				// LABEL  - final
			default:
				break loop
			}
		case 138:
			switch b {
			case 'E', 'e':
				s = 139
			default:
				break loop
			}
		case 139:
			switch b {
			case 'P', 'p':
				s = 140
			default:
				break loop
			}
		case 140:
			switch b {
			case 'O', 'o':
				s = 141
			default:
				break loop
			}
		case 141:
			switch b {
			case 'R', 'r':
				s = 142
			default:
				break loop
			}
		case 142:
			switch b {
			case 'T', 't':
				s = 143
			default:
				break loop
			}
		case 143:
			switch b {
			case ' ':
				s = 144
				m = 6
				// REPORT  - final
			default:
				break loop
			}
		case 145:
			switch b {
			case 'O', 'o':
				s = 146
			default:
				break loop
			}
		case 146:
			switch b {
			case 'R', 'r':
				s = 147
			default:
				break loop
			}
		case 147:
			switch b {
			case 'K', 'k':
				s = 148
			default:
				break loop
			}
		case 148:
			switch b {
			case 'S', 's':
				s = 149
			default:
				break loop
			}
		case 149:
			switch b {
			case 'P', 'p':
				s = 150
			default:
				break loop
			}
		case 150:
			switch b {
			case 'A', 'a':
				s = 151
			default:
				break loop
			}
		case 151:
			switch b {
			case 'C', 'c':
				s = 152
			default:
				break loop
			}
		case 152:
			switch b {
			case 'E', 'e':
				s = 153
			default:
				break loop
			}
		case 153:
			switch b {
			case ' ':
				s = 154
				m = 11
				// MKWORKSPACE  - final
			default:
				break loop
			}
		case 155:
			switch b {
			case 'C', 'c':
				s = 156
			default:
				break loop
			}
		case 156:
			switch b {
			case 'T', 't':
				s = 157
			default:
				break loop
			}
		case 157:
			switch b {
			case 'I', 'i':
				s = 158
			default:
				break loop
			}
		case 158:
			switch b {
			case 'V', 'v':
				s = 159
			default:
				break loop
			}
		case 159:
			switch b {
			case 'I', 'i':
				s = 160
			default:
				break loop
			}
		case 160:
			switch b {
			case 'T', 't':
				s = 161
			default:
				break loop
			}
		case 161:
			switch b {
			case 'Y', 'y':
				s = 162
			default:
				break loop
			}
		case 162:
			switch b {
			case ' ':
				s = 163
				m = 10
				// MKACTIVITY  - final
			default:
				break loop
			}
		case 164:
			switch b {
			case 'A', 'a':
				s = 165
			default:
				break loop
			}
		case 165:
			switch b {
			case 'S', 's':
				s = 166
			default:
				break loop
			}
		case 166:
			switch b {
			case 'E', 'e':
				s = 167
			default:
				break loop
			}
		case 167:
			switch b {
			case 'L', 'l':
				s = 168
			default:
				break loop
			}
		case 168:
			switch b {
			case 'I', 'i':
				s = 169
			default:
				break loop
			}
		case 169:
			switch b {
			case 'N', 'n':
				s = 170
			default:
				break loop
			}
		case 170:
			switch b {
			case 'E', 'e':
				s = 171
			default:
				break loop
			}
		case 171:
			switch b {
			case '_', '':
				s = 172
			default:
				break loop
			}
		case 172:
			switch b {
			case 'C', 'c':
				s = 173
			default:
				break loop
			}
		case 173:
			switch b {
			case 'O', 'o':
				s = 174
			default:
				break loop
			}
		case 174:
			switch b {
			case 'N', 'n':
				s = 175
			default:
				break loop
			}
		case 175:
			switch b {
			case 'T', 't':
				s = 176
			default:
				break loop
			}
		case 176:
			switch b {
			case 'R', 'r':
				s = 177
			default:
				break loop
			}
		case 177:
			switch b {
			case 'O', 'o':
				s = 178
			default:
				break loop
			}
		case 178:
			switch b {
			case 'L', 'l':
				s = 179
			default:
				break loop
			}
		case 179:
			switch b {
			case ' ':
				s = 180
				m = 16
				// BASELINE_CONTROL  - final
			default:
				break loop
			}
		case 181:
			switch b {
			case 'R', 'r':
				s = 182
			default:
				break loop
			}
		case 182:
			switch b {
			case 'G', 'g':
				s = 183
			default:
				break loop
			}
		case 183:
			switch b {
			case 'E', 'e':
				s = 184
			default:
				break loop
			}
		case 184:
			switch b {
			case ' ':
				s = 185
				m = 5
				// MERGE  - final
			default:
				break loop
			}
		case 186:
			switch b {
			case 'N', 'n':
				s = 187
			default:
				break loop
			}
		case 187:
			switch b {
			case 'V', 'v':
				s = 188
			default:
				break loop
			}
		case 188:
			switch b {
			case 'A', 'a':
				s = 189
			default:
				break loop
			}
		case 189:
			switch b {
			case 'L', 'l':
				s = 190
			default:
				break loop
			}
		case 190:
			switch b {
			case 'I', 'i':
				s = 191
			default:
				break loop
			}
		case 191:
			switch b {
			case 'D', 'd':
				s = 192
			default:
				break loop
			}
		case 192:
			switch b {
			case ' ':
				s = 193
				m = 7
				// INVALID  - final
			default:
				break loop
			}
		default:
			break loop
		}
	}

	//fmt.Println("m =", m, "l =", l)

	return m
}
